Выполнена разметка внутренних страниц
htmlacademy-adaptive/106057-cat-energy-25 pull request #3
Opened 2022-04-08 22:49 UTC by dobrjashka145

2022-04-09 19:08 UTC, andreysgra requested changes
В целом, если не считать перечисленного ниже, всё замечательно.

2022-04-09 19:08 UTC, andreysgra commented on source/catalog.html
> +            <img src="img/html academy.svg" width="27" height="34" alt="HTML Academy">
```suggestion
            <img src="img/html-academy.svg" width="27" height="34" alt="HTML Academy">
```
И файл `html academy.svg` нужно переименовать в `html-academy.svg`.

2022-04-09 19:08 UTC, andreysgra commented on source/form.html
> +            <img src="img/html academy.svg" width="27" height="34" alt="HTML Academy">
```suggestion
            <img src="img/html-academy.svg" width="27" height="34" alt="HTML Academy">
```

2022-04-09 19:08 UTC, andreysgra commented on source/catalog.html
> +        <a class="page-header__logo-image">
Нужно добавить ссылку на главную страницу.

2022-04-09 19:08 UTC, andreysgra commented on source/catalog.html
> +        </a>
В логотипе не стоит делать две ссылки (это же ссылка на главную). Либо 2 изображения поместить внутри одной ссылки, либо сделать вообще одно изображение - в фигме объединить два слоя и так экспортировать).

Странно, почему-то этот момент упустил при проверке главной страницы.

2022-04-09 19:08 UTC, andreysgra commented on source/catalog.html
> +              <a class="site-nav__link">главная</a>
Нужно добавить ссылку на главную страницу.

2022-04-09 19:08 UTC, andreysgra commented on source/catalog.html
> +          <a class="show-more__button button button--modify" href="#">заказать</a>
А вот здесь логичнее использовать кнопку, так как логика работы этого элемента реализуется с помощью JS (трудно представить такую страницу, на которой были бы показаны все товары сайта, если их тысячи). Ну и текст в кнопке другой - "показать все".

2022-04-09 19:08 UTC, andreysgra commented on source/catalog.html
> +        <a class="page-footer__logo-name">
Нужно добавить ссылку на главную страницу.

2022-04-09 19:08 UTC, andreysgra commented on source/form.html
> +        </a>
Нужно добавить ссылку на главную страницу.

2022-04-09 19:08 UTC, andreysgra commented on source/form.html
> +              <a class="site-nav__link">главная</a>
Нужно добавить ссылку на главную страницу.

2022-04-10 06:13 UTC, dobrjashka145 commented on source/catalog.html
> +            <img src="img/html academy.svg" width="27" height="34" alt="HTML Academy">
Исправлено

2022-04-10 06:13 UTC, dobrjashka145 commented on source/form.html
> +            <img src="img/html academy.svg" width="27" height="34" alt="HTML Academy">
Исправлено

2022-04-10 06:13 UTC, dobrjashka145 commented on source/catalog.html
> +        <a class="page-header__logo-image">
Исправлено

2022-04-10 06:13 UTC, dobrjashka145 commented on source/catalog.html
> +        </a>
В планшетной и десктопной версии две части логотипа идут одним целым, а в мобильной - как бы отдельно, и текстовая картинка, как мне кажется, центрируется. Из этого и возникли в шапке три отдельных элемента, из которых два - одинаковые ссылки. Если две части логотипа объединить в одну ссылку (в один блок), как потом все грамотно равномерно распределить?

Пока переделала на одну ссылку, содержащую два изображения

2022-04-10 06:13 UTC, dobrjashka145 commented on source/catalog.html
> +              <a class="site-nav__link">главная</a>
Исправлено

2022-04-10 06:13 UTC, dobrjashka145 commented on source/catalog.html
> +          <a class="show-more__button button button--modify" href="#">заказать</a>
В тех. задании сказано: " При отключенном JS должен осуществляться переход на страницу новых товаров." Это будет реализовываться, если здесь поставить кнопку? (я просто не знаю, как это делается). Временно оставляю, как есть.

А вообще, исходя из логики этого блока, напрашивается ссылка на надпись и крестик (но тогда текст должен быть "показать еще 10 товаров", а не тыщу), но это нигде не указано. С другой стороны, если надпись - просто надпись, зачем тогда крестик (на него так и хочется нажать)? В общем, недопродуманная путаница или, наоборот, поле для индивидуального творчества.

2022-04-10 06:13 UTC, dobrjashka145 commented on source/catalog.html
> +        <a class="page-footer__logo-name">
Исправлено

2022-04-10 06:13 UTC, dobrjashka145 commented on source/form.html
> +        </a>
Исправлено

2022-04-10 06:13 UTC, dobrjashka145 commented on source/form.html
> +              <a class="site-nav__link">главная</a>
Исправлено, и ссылки на другие пункты меню тоже.

2022-04-10 06:26 UTC, dobrjashka145 commented on source/form.html
> +              <a class="site-nav__link">главная</a>
А вообще, не льстите. Все идет с большим трудом, работоспособность ниже плинтуса - подсели все защитные батарейки, ну то такое...

2022-04-10 06:34 UTC, dobrjashka145 commented on source/catalog.html
> +          <a class="show-more__button button button--modify" href="#">заказать</a>
Но в планшетной и декстопной версиях этот блок в виде карточки смотрится органично.

2022-04-10 17:37 UTC, andreysgra commented on source/catalog.html
> +        </a>
Начну немного издалека. Раньше графику на курсе адаптивной вёрстки студенты сами не извлекали из макетов и её присылал кексобот. Этот логотип для мобильной версии был представлен одним файлом. Позже авторы курса решили, что студенты сами должны это делать.

Почему я в комментарии написал, что 2 изображения мобильной версии можно объединить в одно - мне это представляется наиболее простым вариантом решения вопроса. Кроме того, я не вижу необходимости в разделении изображений на два. Выделяем в фигме два нужных слоя, в выпадающем меню по клику правой кнопки выбираем пункт "Flatten" и объединённое изображение экспортируем:
![image](https://user-images.githubusercontent.com/17790771/162631735-3f215b43-5c58-4f93-8319-d67292385939.png)

Если же есть желание идти по более сложному пути: как мы видим, начиная с планшетной версии логотип представлен одним изображением и реализация такого поведения вызывает вопросы. Это можно решить, но на данном этапе у вас нет необходимых знаний, так как работу с тегами `picture` и `source` объяснять будут через 2 недели, но я вам приведу пример кода:
```
           <a class="header-logo" aria-label="Логотип сайта Cat Energy">
              <picture>
                <source media="(min-width: 1300px)" srcset="img/logo-desktop.svg">
                <source media="(min-width: 768px)" srcset="img/logo-tablet.svg">
                <img class="header-logo__image" src="img/logo-mobile.svg" alt="Логотип компании" width="34" 
                  height="38">
                <img class="header-logo__image" src="img/logo-mobile.svg" alt="Логотип компании" width="101"
                  height="18">
              </picture>
            </a>
```

Как это работает: то, что указано в теге `img` браузер отображает на любом разрешении экрана, которое меньше 768px, потому сто строкой выше идёт тег `source` с указанием медиа выражения для 768px, а ещё выше, для 1300px. Таким образом для разных разрешений экрана будут использованы свои изображения.

2022-04-10 17:49 UTC, andreysgra commented on source/catalog.html
> +          <a class="show-more__button button button--modify" href="#">заказать</a>
Да, вы правы, есть такая строка в техзадании и несмотря на то, что читал его раз сто, про этот пункт я забыл (с кем не бывает!). Давая вам такой совет я исходил из практической реализации, что подобные интерфейсы без JS не работают. Возьмём к примеру какой-нибудь интернет-магазин. Подобная кнопка добавляет на страницу n-ное количество товаров и размечать этот элемент ссылкой особой нужды нет, так как при отключенном (сломанном) JS переход по ссылке на страницу с десятками тысяч товаров кажется сомнительным. Но я забыл о главном - на кнопке ссылке написано "показать всё" 😄 и это конечно же ссылка!

Что касается крестика - на мой взгляд это кнопка, клик по которой добавляет на страницу какое-то количество товаров. Но в ТЗ этот момент не описан. Я бы разметил этот элемент кнопкой (кстати, можете посмотреть мою собственную реализацию этого проекта в моём аккаунте гитхаба).

2022-04-10 17:55 UTC, andreysgra commented on source/form.html
> +              <a class="site-nav__link">главная</a>
Такое чувство, как лесть мне несвойственно 😃. Встречаются студенты, которые считают, что я их недостаточно хвалю. Это наверное так, потому что если студент сделал плохо или весьма посредственно, то я никак не могу перепрыгнуть через себя, чтобы его похвалить, так как хвалить особо нечего.

Любая учёба требует усилий и порой немалых. Особенно в это немирное время. Несмотря на то, как вы говорите, что всё идёт с большим трудом, у вас всё хорошо получается. Вы человек внимательный, думающий, талантливый и у вас всё будет хорошо.

2022-04-10 17:55 UTC, merged