Адаптивная верстка крупных блоков главной страницы
htmlacademy-adaptive/106057-cat-energy-25 pull request #5
Opened 2022-06-15 04:58 UTC by dobrjashka145

2022-06-16 18:52 UTC, andreysgra requested changes

2022-06-16 18:52 UTC, andreysgra commented on source/index.html
> +        <h2 class="promo__title header-title">Функциональное<br> питание для котов</h2>
Тег `<br>` использовать можно и нужно, но при вёрстке также нужно учитывать ширину элемента, так как искусственный перенос текста может в дальнейшем сыграть злую шутку. Текст в данном макете всего лишь "рыба" и в реально работающем сайте на его месте скорее всего будет другой текст, поэтому, если по дизайну предусматривается перенос текста, но при этом в родительском блоке есть достаточно свободного пространства, то нужно просто ограничить ширину элемента, иначе, может получиться вот так:
![image](https://user-images.githubusercontent.com/17790771/174133444-a2cb1c4c-9dbe-44fe-83db-a70ffa842ab9.png)

2022-06-16 18:52 UTC, andreysgra commented on source/less/page-container.less
> +  }
Здесь есть один важный момент. Изначально в классе `.page-container` (а так как у нас принцип "**mobile first**", то мы задаём параметры для мобильной версии) вы указываете минимальную и максимальную ширину контейнера. Это указывает на то, что контейнер будет иметь гибкую "резиновую" ширину. Такой подход - совмещение адаптивной сетки с резиновой называется "отзывчивой вёрсткой". Но далее, для экрана 768px и 1440px вы задаёте фиксированную ширину контейнера, что по себе отменяет подход "отзывчивая вёрстка", Для начала проще сделать адаптивную сетку с фиксированной шириной контейнера, потому что указание только `min-width` и `max-width` не превращает автоматически вашу вёрстку из адаптивной в отзывчивую.

Для этого свойства `min-width` и `max-width` нужно просто убрать.

Также вам потребуется указать внутренние горизонтальные отступы. Нужно будет либо уменьшить ширину контейнера на ширину отступов (в мобильной версии `width` будет равна 280px), либо изменить алгоритм расчёта размеров блока `box-sizing: border-box`.

2022-06-16 18:52 UTC, andreysgra commented on source/index.html
> +    <main class="page-container">
Теперь по поводу использования класса `page-container`. В нём описаны свойства, которые ограничивают ширину контентной области. Однако в пункте 3.2 ТЗ есть такая формулировка: _Фоны, которые упираются в края макета должны тянуться на всю страницу_. На главной странице есть несколько таких блоков:
![image](https://user-images.githubusercontent.com/17790771/174137255-e887a74d-51d6-4bd6-b394-bab340e7a769.png)
и поэтому применять данный класс, то есть строит контейнер контента, для этих крупных составляющих блоков страницы нельзя:
![image](https://user-images.githubusercontent.com/17790771/174137528-45de895c-1c1e-4900-9f41-7e67ba540ae1.png)
Нужно поступить точно также, как вы делали раньше в "девайсе" - фон, который должен тянуться на всю ширину страницы вешается на родительский блок, а уже внутрь него добавляется блок с классом `page-container` для создания контейнера контента.

2022-06-16 18:52 UTC, andreysgra commented on source/index.html
> +                <dt class="rewiew__value-second">15 000 РУБ.</dt>
Не советую писать текст заглавными буквами, а реализовывать художественные замысли дизайнера средствами CSS. В реальном сайте текст в базе данных может храниться как угодно (в зависимости от того, как введёт текст человек, наполняющий сайт) и если вы будете полагаться только на то, как вы его написали в HTML, то на сайте может оказаться и `кг` и `кГ`. То есть в "рыбе" стоит писать текст общепринятыми нормами языка.

2022-06-16 18:52 UTC, andreysgra commented on source/index.html
> +          <img class="contacts__map-image" src="img/map-mobile.png" width="100%" height="362" alt="Cat Energy на карте.">
Не торопитесь растягивать изображение, подстраивая его под экран. Будет лекция про адаптивные изображения. Так что всему своё время. В `width` укажите реальный размер изображения мобильной версии.

2022-06-16 18:52 UTC, andreysgra commented on source/less/blocks/feed-feature.less
> +    margin-right: 110px;
Думаю, что внешние отступы лучше заменить на внутренние. Внутренние отступы нужны для создания свободного пространства внутри блока, так называемого "воздуха", чтобы контентное содержимое не прилипало к краям блока, а внешние отступы нужны для создания свободного пространства между соседними блоками. Блок, с помощью них либо отталкивается от соседнего блока, либо отталкивает соседний блок (в зависимости от положения блоков).

2022-06-16 18:52 UTC, andreysgra commented on source/less/blocks/feed-feature.less
> +  }
Странноватое решение - в планшетной версии использовать `grid`, а в десктопной версии перейти на `flex`. Вам в десктопной версии нужно просто перестроить шаблон столбцов - было 2, стало 4. И чтобы не писать множество раз одинаковые значения используйте функцию repeat(): `repeat(4, 1fr)`.

2022-06-16 18:52 UTC, andreysgra commented on source/less/blocks/feed-program.less
> +    margin-right: 110px;
Аналогично ранее сказанному: лучше внутренние отступы.

2022-06-16 18:52 UTC, andreysgra commented on source/less/blocks/page-body.less
>  .page-body {
Для `.page-body` нужно указать минимальную ширину. Нужно для того, чтобы ширина контентной области не становилась меньше указанной ширины. Так как у нас ширина мобильной версии равна 320px, то указываем это значение.

2022-06-16 18:52 UTC, andreysgra commented on source/less/blocks/page-header.less
> +    grid-template-rows: 2;
Здесь ошибка синтаксиса. Должен быть указан размер ряда в абсолютных или относительных единицах. А количество рядов указывается перечислением (точно такой же синтаксис, как и для `grid-template-columns`).

2022-06-16 18:52 UTC, andreysgra commented on source/less/blocks/promo.less
> +  }
В десктопной версии блока `.promo` стоит сделать две колонки `grid-template-columns` вместо одной и далее поиграть с расположением внутренних элементов по сетке с помощью свойств `grid-column`, `grid-row`. Таким образом можно избавиться от абсолютного позиционирования изображения `promo__image` (технология Grid поддерживает многослойность с помощью свойства `z-index`).

2022-06-16 18:52 UTC, andreysgra commented on source/less/blocks/site-nav.less
> +    display: flex;
Сразу стоит задумать о переполнение в навигации сайта:
![image](https://user-images.githubusercontent.com/17790771/174144143-64c83b5e-4f19-4db8-8976-673c7724d1f4.png)

2022-06-18 08:16 UTC, dobrjashka145 commented on source/index.html
> +        <h2 class="promo__title header-title">Функциональное<br> питание для котов</h2>
Исправлено. Блоку задана ширина

2022-06-18 08:18 UTC, dobrjashka145 commented on source/less/page-container.less
> +  }
Исправлено

2022-06-18 08:33 UTC, dobrjashka145 commented on source/index.html
> +                <dt class="rewiew__value-second">15 000 РУБ.</dt>
Так было скопировано из фигмы. 
Надписи исправила на строчные, поставила uppercase

2022-06-18 08:34 UTC, dobrjashka145 commented on source/index.html
> +          <img class="contacts__map-image" src="img/map-mobile.png" width="100%" height="362" alt="Cat Energy на карте.">
Исправлено

2022-06-18 08:37 UTC, dobrjashka145 commented on source/less/blocks/feed-feature.less
> +  }
Исправлено

2022-06-18 08:38 UTC, dobrjashka145 commented on source/less/blocks/page-body.less
>  .page-body {
Исправлено

2022-06-18 15:40 UTC, dobrjashka145 commented on source/less/blocks/site-nav.less
> +    display: flex;
Исправлено, наверное.

2022-06-18 15:41 UTC, dobrjashka145 commented on source/less/blocks/promo.less
> +  }
Исправлено

2022-06-18 15:41 UTC, dobrjashka145 commented on source/index.html
> +    <main class="page-container">
Исправлено

2022-06-18 15:46 UTC, dobrjashka145 commented on source/less/blocks/feed-feature.less
> +    margin-right: 110px;
Исправлено

2022-06-18 15:47 UTC, dobrjashka145 commented on source/less/blocks/feed-program.less
> +    margin-right: 110px;
Исправлено

2022-06-18 15:50 UTC, dobrjashka145 commented on source/less/blocks/page-header.less
> +    grid-template-rows: 2;
Исправлено

2022-06-19 07:40 UTC, andreysgra commented on source/index.html
> +                <dt class="rewiew__value-second">15 000 РУБ.</dt>
В макете не всегда написано так, как нужно. Это нужно принимать во внимание.

2022-06-19 07:52 UTC, andreysgra commented on source/less/blocks/promo.less
> +    grid-template-columns: 50%, 50%;
```suggestion
    grid-template-columns: 50% 50%;
```
Иначе ошибка.

2022-06-19 07:52 UTC, andreysgra commented on source/less/blocks/site-nav.less
> +    display: flex;
Не совсем. Не зря, вы засомневались. Перенос пунктов меню нужно сделать когда ширина достигнет примерно этой линии, иначе текст белого цвета будет нечитаемым на белом фоне:
![image](https://user-images.githubusercontent.com/17790771/174471248-549119a6-eb3b-4a1b-b1f6-2218de591f7d.png)

2022-06-19 07:52 UTC, andreysgra approved these changes

2022-06-19 07:52 UTC, merged