Адаптивная верстка страницы формы
htmlacademy-adaptive/106057-cat-energy-25 pull request #6
Opened 2022-06-25 11:23 UTC by dobrjashka145

2022-06-30 08:37 UTC, andreysgra requested changes

2022-06-30 08:37 UTC, andreysgra commented on source/catalog.html
> +      <div class=" inner-header__container page-container">
Этот элемент не может иметь класс `inner-header__container`, так как БЭМ блок `inner-header` не является родительским для него.

2022-06-30 08:37 UTC, andreysgra commented on source/catalog.html
> +          </article>
Стоит ли для данного блока использовать тег `article`. Я думаю, что нет. Этим тегом размечается на сайте самодостаточный контент, при переносе которого в другое место сайта или даже на другой сайт смысл не утрачивается. Для карточек товаров это вполне подходит, а вот для блока "Показать еще" такое решение сомнительное.

2022-06-30 08:37 UTC, andreysgra commented on source/catalog.html
> +            </article>
Здесь почти тоже самое. Вроде бы есть контент, который независим от содержания страницы, но в то же время нет ни описания товара, ни его изображения. Однозначно сказать не могу, что совсем уж нельзя здесь использовать `article`, но я бы не стал. А так, всё на ваше усмотрение.

2022-06-30 08:37 UTC, andreysgra commented on source/catalog.html
> +          </article>
Но вот здесь однозначно `article` использовать не стоит. Ну и к тому же `div.catalog-promo__container` прекрасно справляется с ролью контейнера, так что по сути `article.catalog-promo` лишний элемент разметки.

Не забудьте, когда будете менять разметку, про БЭМ, так как `article.catalog-promo` у вас БЭМ блок и от него строится именование классов дочерних элементов.

2022-06-30 08:37 UTC, andreysgra commented on source/catalog.html
> +            <img src="img/icons/menu-open.png" width="24" height="16" alt="Открыть меню">
Я этот момент упустил на главной странице, но хорошо, что сейчас заметил. Это изображение декоративное, следовательно его не нужно добавлять в разметку.

2022-06-30 08:37 UTC, andreysgra commented on source/less/blocks/add-goods.less
> +  }
На разрешении экрана 1440px всё выглядит вроде бы хорошо:
![image](https://user-images.githubusercontent.com/17790771/176625708-612d7a00-d287-49d6-ba85-4f99197ce88e.png)
но если мы увеличим разрешение экрана, то увидим, что текст заголовка смещается влево и находится за пределами сетки:
![image](https://user-images.githubusercontent.com/17790771/176626048-0b7b8133-1326-4dd2-8a60-da763c2439d7.png)

Проблема в абсолютном позиционировании `.add-goods__title` (но это можно решить) и в том, что у вас привязка левой координаты (`left: 0`) не изменяется в зависимости от разрешения экрана, а свиг `.add-goods__title` производится за счёт фиксированного значения `margin-left`. Если идти по пути абсолютно позиционированного элемента, то привязку координат нужно рассчитывать через функцию `calc()` и использовать при этом значения в процентах. Зелёную линию нужно повесить псевдо элементом на сам `.add-goods__title`, а не делать как рамку родительского блока `.add-goods`.

Решения могут быть разными, можете посмотреть мой вариант. Он не совсем простой, но вполне рабочий и даже на экране в 2560px всё смотрится корректно:
![image](https://user-images.githubusercontent.com/17790771/176627590-e81e4f39-8178-42d8-90ff-ec959f2b6a73.png)

Но всё это к заданию по сеткам не относится, поэтому решение вопроса можно отложить на более поздние задания.

2022-06-30 08:37 UTC, andreysgra commented on source/less/blocks/addition-card.less
> +    grid-template-columns: 300px 1fr 1fr;
На мой взгляд здесь шаблон колонок (`grid-template-columns`) нужно задать иначе. В шаблоне три колонки, ширина контента в последней колонке изменяться не будет, так как там кнопка с фиксированной шириной. Следовательно значение в `px` лучше задать для неё.

2022-06-30 08:37 UTC, andreysgra commented on source/less/blocks/catalog-promo.less
> +    display: inline-block;
Вам не кажется странным изменение значения свойства `display` для параграфа `catalog-promo__slogan`. Я не вижу в этом необходимости.

2022-06-30 08:37 UTC, andreysgra commented on source/less/blocks/form-fieldset.less
> +  justify-content: flex-start;
`flex-start` значение по умолчанию для свойства `justify-content` поэтому можно не указывать. Имело бы смысл, если к примеру в мобильной версии было бы другое выравнивание вдоль главной оси, а в планшетной версии нужно было бы вернуть к исходному состоянию.

2022-06-30 08:37 UTC, andreysgra commented on source/less/blocks/form-fieldset.less
> +  gap: 15px;
Поскольку здесь одна колонка и собственно `grid` вы используете только для задания расстояния между рядами, то свойства `grid-template-columns`, `grid-template-rows` можно не задавать. Но а по большому счёту здесь `grid` и вовсе не нужен, так как расстояние можно задать с помощью `margin-bottom`, а расположение блоков, как в стандартной блочной модели, поэтому необходимости изменять свойство `display` нет.

2022-06-30 08:37 UTC, andreysgra commented on source/less/blocks/show-more.less
> +    height: 430px;
` height: 430px`: а если контента будет больше, тогда он выйдет за пределы блока.

2022-07-01 20:52 UTC, dobrjashka145 commented on source/catalog.html
> +      <div class=" inner-header__container page-container">
Исправлено

2022-07-02 04:48 UTC, dobrjashka145 commented on source/catalog.html
> +          </article>
Исправлено.

2022-07-02 06:03 UTC, dobrjashka145 commented on source/catalog.html
> +            </article>
Исправлено.

И здесь то же самое. Мне постоянно хочется использовать тег article для формального разделения логически обособленных блоков в пределах раздела. А с семантикой, особенно с определением самодостаточности контента у меня большие проблемы.

2022-07-02 06:08 UTC, dobrjashka145 commented on source/catalog.html
> +          </article>
Исправлено

2022-07-02 07:13 UTC, dobrjashka145 commented on source/less/blocks/show-more.less
> +    height: 430px;
Исправлено на min-height:

2022-07-02 09:27 UTC, dobrjashka145 commented on source/less/blocks/catalog-promo.less
> +    display: inline-block;
Исправлено.

2022-07-02 16:47 UTC, dobrjashka145 commented on source/catalog.html
> +            <img src="img/icons/menu-open.png" width="24" height="16" alt="Открыть меню">
Исправлено.

2022-07-03 04:28 UTC, dobrjashka145 commented on source/less/blocks/add-goods.less
> +  }
Оставлено на потом.

2022-07-03 04:28 UTC, dobrjashka145 commented on source/less/blocks/addition-card.less
> +    grid-template-columns: 300px 1fr 1fr;
Исправлено.

2022-07-03 04:40 UTC, dobrjashka145 commented on source/less/blocks/form-fieldset.less
> +  justify-content: flex-start;
Исправлено.

2022-07-03 05:35 UTC, dobrjashka145 commented on source/less/blocks/form-fieldset.less
> +  gap: 15px;
Убрала свойства grid-template-columns, grid-template-rows. 

Полностью убрать в этом месте grid не получится, поскольку у .form-fieldset__list, для которого он задан есть две модификации: .form-fieldset__list--radio, который остается блочным, и .form-fieldset__list--checkbox, который потом перестраивается в grid. Так вот, если задать отступ margin-bottom для класса .form-fieldset__list, то потом нельзя его убрать для модификации  .form-fieldset__list--checkbox, когда она становится grid-ом и этот отступ становится лишним (особенно в планшетной версии, с двумя колонками), поскольку это свойство остается в основном классе. Собственно, из-за этого и появилась данная конструкция.

2022-07-03 12:42 UTC, andreysgra commented on source/catalog.html
> +          </article>
Нет, это не такая же карточка, как и карточка товара. Карточки товара можно объединить в список, так как это очень схожие сущности. Добавлять данный блок в такой список нельзя (очень распространённая проблема в студенческих проектов), так как у него совершенно иной смысл.

2022-07-03 12:46 UTC, merged