Декоративные элементы главной страницы
htmlacademy-adaptive/106057-cat-energy-25 pull request #7
Opened 2022-07-09 19:47 UTC by dobrjashka145

2022-07-15 10:14 UTC, andreysgra requested changes
Ещё обратите внимание на главную страницу. Есть горизонтальная полоса прокрутки
![image](https://user-images.githubusercontent.com/17790771/179203373-c676d7a7-91e5-43c3-81e3-a90682e133bc.png)
Это говорит о том, что какой-то элемент выходит за пределы заданных границ сетки.

2022-07-15 10:14 UTC, andreysgra commented on source/form.html
> +            <div class="form-fieldset__container form-fieldset--comment">
Класс модификатора изменяет свойства класса БЭМ блока или БЭМ элемента. Класс `form-fieldset--comment` должен модифицировать свойства блока `form-fieldset`. Где здесь этот блок? 😏

2022-07-15 10:14 UTC, andreysgra commented on source/form.html
> +            <div class="form-fieldset__container form-fieldset--checkbox">
Класс `form-fieldset--checkbox` - точно такая же ошибка.

2022-07-15 10:14 UTC, andreysgra commented on source/form.html
> +            <div class="form-fieldset__container form-fieldset__container--input form-fieldset__container--input2">
В качестве рекомендации: я бы не советовал использовать классы с цифрами в названии типа `form-fieldset__container--input2`, так как цифра не даёт представление для какого элемента используется данный класс.

2022-07-15 10:14 UTC, andreysgra commented on source/index.html
> +            <img class="gallery__image visually-hidden" src="img/content/cat-skinny-mobile.png" width="280" height="267" alt="Худой кот после программы фитнес-питания.">
Нет необходимости доступно прятать одно из изображений слайда. Эффект плавной смены изображений должен строится по принципу, что одно изображение находится поверх другого.

Должен быть общий контейнер для всех изображений и отдельные контейнеры для каждого изображения:
![image](https://user-images.githubusercontent.com/17790771/179197732-f4447a74-c35f-4b7d-bd82-5ea99f542e95.png)

Далее изменяется только ширина контейнера верхнего изображения. Изначально ширину задаём равной 50%, чтобы показать половинки двух изображений:
![image](https://user-images.githubusercontent.com/17790771/179198259-6a1bb33b-052f-43bf-8d9a-01b3ac879246.png)

Если ширину задать 100%, то нижнее изображение будет полностью перекрыто верхним:
![image](https://user-images.githubusercontent.com/17790771/179198570-7a3445b4-b944-4ade-9c9f-c7280cccf4d1.png)

И соответственно если ширина контейнера верхнего изображения будет равно 0%, то нижнее изображение будет видно полностью:
![image](https://user-images.githubusercontent.com/17790771/179198854-17cd1519-c9ec-465e-aa59-07b365c0d96f.png)

Поэтому, чтобы сделать анимацию слайдов с помощью JS более просто, необходимо написать хорошие стили CSS. Теперь с помощью JS нужно будет всего лишь изменять значение свойства `width` верхнего контейнера.

2022-07-15 10:14 UTC, andreysgra commented on source/js/nav-toggle.js
> +let navToggle = document.querySelector('.page-header__nav-toggle');
У нас конечно здесь только вёрстка и JS мы не затрагиваем, но поясню для общего понимания. В современном синтаксисе ECMAScript-2015 для обозначения переменных используются два ключевых слова `let` и `const`.

`let` используется для создания переменной значение которой в процессе работы программы может изменяться. Например, в первой строке кода вы находите HTML элемент с классом `.site-nav` и присваиваете его значение переменной `navSite`. Соответственно по ходу программы, если вас значение переменной `navSite` больше не интересует, вы можете присвоить ей другое значение: `navSite = document.querySelector('.promo__title header-title')`.

`const` используется для создания переменной значение которой в процессе работы программы **не изменяется**. Если сделать объявление `const navSite = document.querySelector('.site-nav');`, а потом `navSite = document.querySelector('.promo__title header-title')` возникнет ошибка.

Как правило, в программах для таких случаев, как присваивание переменной значения HTML элемента используют `const`, так как значение этой переменной не должно изменяться по ходу программы.

2022-07-15 10:14 UTC, andreysgra commented on source/less/blocks/feed-feature.less
> +    content: "4";
Чтобы не указывать для каждого элемента списка своё значение можно запустить счётчик через свойство `content`.Более подробно[ здесь](https://webref.ru/css/counter-reset) и в качестве примера моя вёрстка этого макета.

2022-07-16 02:18 UTC, dobrjashka145 commented on source/form.html
> +            <div class="form-fieldset__container form-fieldset--comment">
Исправлено на form-fieldset__container--comment

2022-07-16 02:19 UTC, dobrjashka145 commented on source/form.html
> +            <div class="form-fieldset__container form-fieldset--checkbox">
Исправлено на form-fieldset__container--checkbox

2022-07-16 02:22 UTC, dobrjashka145 commented on source/form.html
> +            <div class="form-fieldset__container form-fieldset__container--input form-fieldset__container--input2">
Исправлено на form-fieldset__container--input-contacts

2022-07-16 08:11 UTC, dobrjashka145 commented on source/index.html
> +            <img class="gallery__image visually-hidden" src="img/content/cat-skinny-mobile.png" width="280" height="267" alt="Худой кот после программы фитнес-питания.">
Исправлено, но, может быть, коряво.
И я не знаю, как стилизовать бегунок.

2022-07-16 15:25 UTC, dobrjashka145 commented
Свои ошибки, ответственные за появление горизонтальной полосы прокрутки, я вроде бы исправила. Но эта полоса появляется временно, когда ширина контейнера примерно равна ширине окна браузера из-за того, что 20рх занимает справа вертикальная полоса прокрутки. Я помню, что нам на какой-то лекции говорили о том, что на планшете и десктопе контейнер не должен прилипать к стенкам окна браузера, его ширина должна быть меньше 100%, но я не смогла найти это место ни в лекции, ни в верстке. Не могли бы вы мне помочь?

2022-07-16 15:30 UTC, dobrjashka145 commented on source/js/nav-toggle.js
> +let navToggle = document.querySelector('.page-header__nav-toggle');
Исправлено.
Здесь я просто вставила то, что нам дали на лекции.

2022-07-16 15:50 UTC, dobrjashka145 commented on source/less/blocks/feed-feature.less
> +    content: "4";
Исправлено

2022-07-17 09:17 UTC, andreysgra approved these changes

2022-07-17 09:17 UTC, andreysgra commented on source/less/blocks/add-goods.less
>  .add-goods__title {
Так как стилизация данных элементов интерфейса на странице каталога и странице формы выглядит одинаково, то стоит использовать один класс. В моей вёрстке это `heading`. Но так как он применяется к разным тегам, то потребуются дополнительные классы, в которых будут описаны свойства необходимые для конкретного тега.

2022-07-17 09:17 UTC, merged