Адаптивная графика всех страниц
htmlacademy-adaptive/106057-cat-energy-25 pull request #8
Opened 2022-07-22 03:38 UTC by dobrjashka145

2022-07-23 07:57 UTC, andreysgra requested changes

2022-07-23 07:57 UTC, andreysgra commented on source/catalog.html
>                  </a>
Отсутствует закрывающий тег `</picture>`.

2022-07-23 07:57 UTC, andreysgra commented on source/catalog.html
> +        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1998.6026570763552!2d30.321738470254086!3d59.9387352341448!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4696310fca145
Ошибка валидации HTML:
![image](https://user-images.githubusercontent.com/17790771/180595583-b3472b98-db74-4897-978b-f90d64b2d6a1.png)

Не знаю, почему Google выдаёт невалидный код, но атрибуты `width` и `height` нужно убрать, а размеры задать через CSS.

Нужно исправить для всех страниц.

2022-07-23 07:57 UTC, andreysgra commented on source/less/blocks/catalog-promo.less
> +    background-image: url("../img/catalog-bg-mobile@1x.jpg");
Для экрана с двойной плотностью пикселей нужна картинка **catalog-bg-mobile@2x**.

2022-07-23 07:57 UTC, andreysgra commented on source/less/blocks/catalog-promo.less
> +    background-image: url("../img/catalog-bg-tablet@2x.jpg");
А здесь, где экран с обычной плотностью пикселей нужна картинка **catalog-bg-tablet@1x**.

2022-07-23 07:57 UTC, andreysgra commented on source/less/blocks/page-header.less
> +    background-size: image-size("../img/index-bg-desktop@1x.jpg"), 100%;
В своей вёрстке для определения размера изображения я использовал функцию Less `image-size()`. Думаю, что вы с этим разобрались.

2022-07-23 08:11 UTC, dobrjashka145 commented on source/catalog.html
>                  </a>
Исправлено

2022-07-23 08:15 UTC, dobrjashka145 commented on source/catalog.html
> +        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1998.6026570763552!2d30.321738470254086!3d59.9387352341448!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4696310fca145
Исправлено.

2022-07-23 08:31 UTC, dobrjashka145 commented on source/less/blocks/catalog-promo.less
> +    background-image: url("../img/catalog-bg-mobile@1x.jpg");
Исправлено

2022-07-23 08:32 UTC, dobrjashka145 commented on source/less/blocks/catalog-promo.less
> +    background-image: url("../img/catalog-bg-tablet@2x.jpg");
Исправлено

2022-07-23 09:18 UTC, dobrjashka145 commented on source/less/blocks/page-header.less
> +    background-size: image-size("../img/index-bg-desktop@1x.jpg"), 100%;
Да, я с этим разобралась.

2022-07-25 07:03 UTC, andreysgra approved these changes

2022-07-25 07:03 UTC, andreysgra commented on source/index.html
> +                  rcset="img/content/index-promo-tablet@1x.png 1x, img/content/index-promo-tablet@2x.png 2x">
```suggestion
                  srcset="img/content/index-promo-tablet@1x.png 1x, img/content/index-promo-tablet@2x.png 2x">
```

2022-07-25 07:03 UTC, merged