Добавлена автоматическая сборка проекта
htmlacademy-adaptive/106057-cat-energy-25 pull request #9
Opened 2022-07-30 03:13 UTC by dobrjashka145

2022-07-31 18:15 UTC, andreysgra requested changes

2022-07-31 18:15 UTC, andreysgra commented on gulpfile.js
> +import { deleteAsync } from 'del'; 'del';
Кое что лишнее. Должно быть так:
```suggestion
import { deleteAsync } from 'del';
```

2022-07-31 18:15 UTC, andreysgra commented on gulpfile.js
>      .pipe(gulp.dest('source/css', { sourcemaps: '.' }))
```suggestion
    .pipe(gulp.dest('build/css', { sourcemaps: '.' }))
```

2022-07-31 18:15 UTC, andreysgra commented on gulpfile.js
>      ]))
Нужно добавить сжатие CSS плагином CSSO:
```suggestion
    .pipe(postcss([
      autoprefixer(),
      csso()
    ]))
```

2022-07-31 18:15 UTC, andreysgra commented on gulpfile.js
> +}
А это задание стоит выкинуть за ненадобностью, так как всё будет делаться в задании **styles**.

2022-07-31 18:15 UTC, andreysgra commented on gulpfile.js
> +    .pipe(rename('style.css'))
```suggestion
    .pipe(rename('style.min.css'))
```

2022-07-31 18:15 UTC, andreysgra commented on gulpfile.js
> +function server(done) {
Зачем стрелочную функцию `const server = (done) => {`, заменили на объявление функции `function server(done) {`. Непонятно.

Ну и baseDir должен указывать на каталог `build`.

Всё задание `server`:
```
const server = (done) => {
  browser.init({
    server: {
    baseDir: 'build'
  },
    cors: true,
    notify: false,
    ui: false,
  });
    done();
}
```

2022-07-31 18:15 UTC, andreysgra commented on gulpfile.js
> +  gulp.watch('source/js/*.js').on('change', browser.reload);
При такой записи, как сейчас, у вас будет просто перезагружаться страница в браузере, но задание `minJS` не запустится.

Правильно: `gulp.watch('source/js/*.js', gulp.series(minJS));`

2022-07-31 18:15 UTC, andreysgra commented on gulpfile.js
> +    minCSS,
Так как компиляция и сжатие CSS будет происходить в рамках одного задания `styles`, то `minCSS` нужно здесь убрать.

2022-07-31 18:15 UTC, andreysgra commented on gulpfile.js
>    styles, server, watcher
Эта функция будет запускаться по команде `npm start` (смотрите строку 33 файла package.json). Поэтому здесь должны быть практически все те же задания, что и в задании build, которое запускается командой `npm run build`. Можно было бы всё описать так:
```
export default gulp.series(
  build, server, watcher
);
```
но есть нюанс, что задание по оптимизации графики `imagesOpti` отнимает ресурсы и соответственно время, поэтому нужно создать отдельное задание по копированию графики без оптимизации (по аналогии с заданием `copyFiles`) и переписать данный код примерно так:
```
export default gulp.series(
  clean,
  copyImages,
  gulp.parallel(
    copyFiles,
    styles,
    minJS,
    createWebp,
    spriteSvg
  ),
  gulp.series(
    server,
    watcher
  )
);
```
где **copyImages** задание по копированию графики (задание imagesOpti убрано).

2022-07-31 18:29 UTC, dobrjashka145 commented on gulpfile.js
> +import { deleteAsync } from 'del'; 'del';
Исправлено

2022-07-31 22:45 UTC, dobrjashka145 commented on gulpfile.js
> +function server(done) {
Не знаю, как так случилось, что функции поменялись, правда. Я тут вообще боялась что-либо менять. И источник замены не нашла. На минутку вышел из себя, когда вернулся, оно уже такое было...

2022-07-31 23:14 UTC, dobrjashka145 commented on gulpfile.js
> +  gulp.watch('source/js/*.js').on('change', browser.reload);
Исправлено

2022-07-31 23:15 UTC, dobrjashka145 commented on gulpfile.js
> +    minCSS,
Исправлено

2022-07-31 23:18 UTC, dobrjashka145 commented on gulpfile.js
>    styles, server, watcher
Исправлено

2022-07-31 23:55 UTC, dobrjashka145 commented on gulpfile.js
>      ]))
Переделаны задания styles, minJS.
Удалено задание minCSS.

В задании styles я не знаю, как правильно добавить сжатие и переименование для style.css. Нужные файлы создаются, из build страницы запускаются правильно, но из-за этой вставки в код не может завершиться выполнение самого задания styles и запуститься локальный сервер с командой start.

2022-08-01 16:07 UTC, andreysgra requested changes

2022-08-01 16:07 UTC, andreysgra commented on gulpfile.js
>  // Styles
Вот такой код будет работать:
```
export const styles = () => {
  return gulp.src('source/less/style.less', { sourcemaps: true })
    .pipe(plumber())
    .pipe(less())
    .pipe(postcss([
      autoprefixer(),
      csso()
    ]))
    .pipe(rename('style.min.css'))
    .pipe(gulp.dest('build/css', { sourcemaps: '.' }))
    .pipe(browser.stream());
}
```
но придётся пожертвовать несжатым файлом ccs. Как я уже говорил, в готовом проекте он и не нужен, так как исходный код находится в файлах Less.

В вашем коде много лишнего:
1. autoprefixer и csso плагины пакета postcss следовательно их можно объединить в рамках одного процесса.
2. `rename('style.css')` делать не нужно, так как файл который обрабатывает Less называется style и на выходе мы получим файл с точно таким же именем.

Ошибка сборки происходит при обработке файла карты кода style.css.map плагином csso, если стоит задача получения несжатого файла style.css. Как обойти эту проблему и почему она возникает, я честно говоря не знаю.

2022-08-02 06:38 UTC, merged